#!/bin/bash

if which systemctl >/dev/null >/dev/null 2>&1 ; then
	systemctl disable proxywise || true
	systemctl stop proxywise || true

elif which service >/dev/null 2>&1 ; then
	service proxywise stop || true
fi
