#!/bin/sh

if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-light /usr/share/icons/ubuntu-mono-dark /usr/share/icons/hicolor || true
fi

if which gtk-update-icon-cache >/dev/null 2>&1 ; then
	gtk-update-icon-cache --force --quiet /usr/share/icons/ubuntu-mono-light /usr/share/icons/ubuntu-mono-dark /usr/share/icons/hicolor || true
fi

if which systemctl >/dev/null >/dev/null 2>&1 ; then
	systemctl enable proxywise || true
	systemctl start proxywise || true

elif which service >/dev/null 2>&1 ; then
	service proxywise start || true

else
	echo "Unable to autostart proxywise-service"
fi
